name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  # 1. System Overlays
  - type: files
    files:
      - source: system
        destination: /

  # 2. Core Infrastructure (RPMs)
  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - gnome-software
      - firefox
      - firefox-langpacks

  # 3. User Space Apps (Flatpaks)
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Browsers ---
        - org.mozilla.firefox

        # --- System & Management ---
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - io.missioncenter.MissionCenter

        # --- Development ---
        - dev.zed.Zed

  # 4. Fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter

  # 5. Background Services
  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
