name: wavyos
description: Debug Build (Skeleton)
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  # FLATPAKS (v1 Syntax - Final Safe List)
  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Core Browsers ---
        - org.mozilla.firefox
        - org.chromium.Chromium

        # --- Productivity & Notes ---
        - md.obsidian.Obsidian
        - org.gnome.Papers

        # --- Development ---
        - dev.zed.Zed
        - org.gnome.Builder
        - re.sonny.Workbench
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - io.missioncenter.MissionCenter
        - org.gnome.baobab
        - org.gnome.Connections

        # --- GNOME Core / Utilities ---
        - com.mattjakeman.ExtensionManager
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Logs
        - org.gnome.Loupe
        - app.drey.Warp

        # --- Media & Gaming ---
        - io.bassi.Amberol
        - de.haeckerfelix.Shortwave
        - org.gnome.Podcasts
        - io.github.celluloid_player.Celluloid
        - com.github.wwmm.easyeffects
        - org.gnome.Games

  # FONTS (Monaspace Nerd Font)
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter
        - Roboto
        - Open Sans
      url-fonts:
        - name: Monaspace
          url: https://github.com/githubnext/monaspace/releases/download/v1.301/monaspace-nerdfonts-v1.301.zip

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer