name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Browsers ---
        - org.mozilla.firefox
        - org.chromium.Chromium

        # --- System & Management ---
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - io.missioncenter.MissionCenter
        - org.gnome.baobab
        - org.gnome.Logs
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - io.github.giantpinkrobots.flatsweep

        # --- Development ---
        - dev.zed.Zed
        - com.github.marhkb.Pods
        - org.gnome.Boxes
        - org.gnome.Builder
        - re.sonny.Workbench
        - app.drey.Warp
        - com.raggesilver.BlackBox
        - com.vscodium.codium

        # --- Productivity ---
        - md.obsidian.Obsidian
        - org.gnome.Papers
        - org.gnome.World.PikaBackup
        - dev.geopjr.Tuba
        - com.ranfdev.DistroShelf

        # --- Creative & Media ---
        - io.bassi.Amberol
        - de.haeckerfelix.Shortwave
        - org.gnome.Podcasts
        - io.github.celluloid_player.Celluloid
        - org.gnome.Loupe
        - com.github.wwmm.easyeffects

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter
        - Roboto
        - Open Sans
      url-fonts:
        - name: Monaspace
          url: https://github.com/githubnext/monaspace/releases/download/v1.301/monaspace-nerdfonts-v1.301.zip

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
