name: wavyos
description: Debug Build (Skeleton)
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
