name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - gnome-software
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Browsers ---
        - org.mozilla.firefox

        # --- System ---
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - io.missioncenter.MissionCenter
        
        # --- Dev ---
        - dev.zed.Zed

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
