name: wavyos
description: Debug Build (Skeleton)
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  # FLATPAKS V2 SYNTAX (Core Only)
  - type: default-flatpaks
    notify: true
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (System)"
        install:
          # --- Core Browsers ---
          - org.mozilla.firefox
          - org.chromium.Chromium

          # --- System Tools ---
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.missioncenter.MissionCenter

          # --- Dev ---
          - dev.zed.Zed

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter
        - Roboto
        - Open Sans

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
