name: wavyos
description: Debug Build (Skeleton)
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  # FLATPAKS (v1 - Host Verified List)
  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Core Browsers ---
        - org.mozilla.firefox
        - org.chromium.Chromium

        # --- System & Management ---
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - io.missioncenter.MissionCenter
        - org.gnome.baobab                  # Disk Usage
        - org.gnome.Logs
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - io.github.giantpinkrobots.flatsweep

        # --- Development ---
        - dev.zed.Zed
        - com.github.marhkb.Pods
        - org.gnome.Boxes
        - org.gnome.Builder
        - re.sonny.Workbench
        - app.drey.Warp
        - com.raggesilver.BlackBox
        - com.vscodium.codium

        # --- Productivity ---
        - md.obsidian.Obsidian
        - org.gnome.Papers                  # PDFs
        - org.gnome.World.PikaBackup
        - dev.geopjr.Tuba                   # Mastodon
        - com.ranfdev.DistroShelf           # Android Bridge

        # --- Creative & Media ---
        - io.bassi.Amberol
        - de.haeckerfelix.Shortwave
        - org.gnome.Podcasts
        - io.github.celluloid_player.Celluloid
        - org.gnome.Loupe                   # Image Viewer
        - com.github.wwmm.easyeffects       # Audio EQ

        # Removed: Spotube, Steam, Games, Audio Plugins (Auto-dependency)

  # FONTS (Monaspace Nerd Font)
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter
        - Roboto
        - Open Sans
      url-fonts:
        - name: Monaspace
          url: https://github.com/githubnext/monaspace/releases/download/v1.301/monaspace-nerdfonts-v1.301.zip

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
