name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  # 1. System Overlays
  - type: files
    files:
      - source: system
        destination: /

  # 2. Core Infrastructure
  - type: rpm-ostree
    install:
      - fish
      - zsh

  # 3. Font Support
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode

  # 4. Background Services (Auto-Updates)
  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer   # OS Updates
        - flatpak-system-update.timer   # App Updates
