name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  # 1. System Overlays
  - type: files
    files:
      - source: config/files
        destination: /

  # 2. Core Infrastructure (Minimal)
  - type: rpm-ostree
    install:
      # --- Shell Essentials ---
      - fish
      - starship
      
      # --- Bootstrapping Tools ---
      # Needed to run 'just setup' / Homebrew
      - git
      - wget
      - curl
      
      # --- Asahi Hardware Support ---
      - asahi-bless
      - asahi-scripts

  # 3. Font Support (Keep this, it's low risk and high UI value)
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
