name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  # 1. System Overlays
  # Now points to the 'system' folder we just created
  - type: files
    files:
      - source: system
        destination: /

  # 2. Core Infrastructure
  - type: rpm-ostree
    install:
      - fish
      - zsh

  # 3. Font Support
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
