name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - spice-vdagent
      - ptyxis
      - gnome-console
    remove:
      - gnome-tour

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
        - spice-vdagentd.service
