name: wavyos
description: A polished, immutable Fedora Asahi Remix experience.
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  # FLATPAKS V2 MIGRATION
  - type: default-flatpaks
    notify: true
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (System)"
        install:
          # --- Browsers ---
          - org.mozilla.firefox
          - org.chromium.Chromium

          # --- System & Management ---
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - io.missioncenter.MissionCenter
          - org.gnome.baobab
          - org.gnome.dconf-editor
          - org.gnome.Logs
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections

          # --- Development ---
          - dev.zed.Zed
          - com.github.marhkb.Pods
          - org.gnome.Boxes
          - org.gnome.Builder
          - re.sonny.Workbench
          - app.drey.Warp

          # --- Creative & Media ---
          - io.bassi.Amberol
          - de.haeckerfelix.Shortwave
          - org.gnome.Podcast
          - io.github.celluloid_player.Celluloid
          - org.gnome.Loupe
          - org.gnome.Papers
          - com.github.wwmm.easyeffects

          # --- Gaming ---
          - org.gnome.Games
          - net.retrodeck.retrodeck

          # --- Productivity ---
          - org.gnome.World.PikaBackup
          - app.getapostrophe.Apostrophe

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer