name: wavyos
description: Debug Build (Skeleton)
base-image: quay.io/fedora-asahi-remix-atomic-desktops/silverblue
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fish
      - zsh
      - ptyxis
      - gnome-tweaks
      - steam-devices
    remove:
      - gnome-tour
      - firefox
      - firefox-langpacks

  # FLATPAKS (v1 Syntax - Expanded)
  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        # --- Core Browsers ---
        - org.mozilla.firefox
        - org.chromium.Chromium

        # --- Productivity & Notes ---
        - md.obsidian.Obsidian              # Added: Obsidian
        - app.getapostrophe.Apostrophe      # Markdown Editor
        - org.gnome.Papers                  # PDFs

        # --- Development ---
        - dev.zed.Zed                       # Added: Zed (ARM64 Check)
        - io.github.flattool.Warehouse
        - io.github.kolunmi.Bazaar
        - com.github.tchx84.Flatseal
        - io.missioncenter.MissionCenter
        - org.gnome.baobab                  # Disk Usage
        - org.gnome.Connections             # VNC/RDP

        # --- GNOME Core (Replacements) ---
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Logs
        - org.gnome.Loupe                   # Image Viewer

        # --- Media ---
        - io.bassi.Amberol
        - io.github.celluloid_player.Celluloid
        - com.github.wwmm.easyeffects

  # FONTS (Monaspace Nerd Font)
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - FiraCode
      google-fonts:
        - Inter
        - Roboto
        - Open Sans
      url-fonts:
        - name: Monaspace
          url: https://github.com/githubnext/monaspace/releases/download/v1.301/monaspace-nerdfonts-v1.301.zip

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
