FROM quay.io/fedora-asahi-remix-atomic-desktops/silverblue:42

# 1. Install VM Bootloader Tools
RUN rpm-ostree install \
    grub2-efi-aa64 \
    grub2-efi-aa64-modules \
    grub2-tools \
    shim-aa64 \
    plymouth-plugin-script \
    && rpm-ostree cleanup -m

# 2. Setup Build Context
COPY config /tmp/config

# 3. Apply System Files (FIXED)
# We use 'cp -a src/.' to merge contents into existing system directories
RUN cp -a /tmp/config/files/usr/. /usr/ && \
    cp -a /tmp/config/files/etc/. /etc/

# 4. Run Modules
RUN chmod +x /tmp/config/modules/*.sh && \
    /tmp/config/modules/01-packages.sh && \
    /tmp/config/modules/02-tweaks.sh

# 5. Cleanup
RUN rm -rf /tmp/* /var/tmp/*

# 6. Unlock Root (For VM debugging)
RUN echo "root:fedora" | chpasswd
